{
    'name': "Clinic Management",
    'version': '1.0.01',
    'category':'Clinic',
    'website': 'https://www.dishicreation.com',
    'author':'Dishi creation',
    'sequence':'-200',
    'summary': 'Clinic managemnet system',
    'description': "Clinic management",
    'depends': ['mail','product'],
    'data': [
            'security/ir.model.access.csv',
            'views/menu.xml',
            'views/patient_details_view.xml',
            'views/appointments_view.xml',
            'views/patient_medicine_view.xml',      
    ],
    'demo': [],
    'installable': True,
    'auto install':'False',
    'application': True,
    'license': 'LGPL-3',
    'sequence': 3,
}
